version: '3.8'

services:
  app:
    build: .
    container_name: teddy-finance-app
    restart: always
    ports:
      - '3000:3000' # Certifique-se de expor a porta correta da aplicação
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/teddy-finance-db
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: teddy-finance-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teddy-finance-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
